sudo: required
services:
  - docker

before_install:
  - docker build -t shashwatmath/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shashwatmath/docker-react npm run test -- --watchAll=false

deploy:
  provider: azure_web_apps