sudo: required
services:
  - docker

before_install:
  - docker build -t -f Dockerfile.dev shashwatmath/docker-react .

script:
  - docker run -e CI=true shashwatmath/docker-react npm run test -- --watchAll=false